cask "docker"
cask "emacs"
cask "iterm2"
cask "osxfuse"
cask "spotify"

brew "bash-completion"
brew "go"
brew "mas"
brew "python"

brew "git-lfs"

# For emacs image-dired thumbnails.
brew "imagemagick"

brew "ffmpeg"
